### PR TITLE
fixing a list

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by jtaubensee** [comment]
@SeanFeldman - what does this fix?

**Comment by SeanFeldman** [comment]
Lists items in markdown should be all prefixed with "1." to allow easy re-arrangement w/o changing the numbering. MD automatically increase numbering in the list.

**Comment by jtaubensee** [comment]
True..... but its not broken.

**Comment by SeanFeldman** [comment]
A markdown purist would say it is 😃

**Pull request merged**
